### ISSUE TITLE
Any chance we can get a unpack function as well?

### ISSUE THREAD

**Issue by alimoeeny** [FatihBAKIR/UnityPacker#1]
Hi @FatihBAKIR 
Basically my use case is to duplicate a scene, to do that I need to export as a package, unpack, rename all the paths, repack, import.

**Comment by FatihBAKIR** [comment]
@alimoeeny, could be useful, but I'm a bit busy right now to implement it. I would be happy to merge if you'd implement it though. I've seen some repos that unpacks a unitypackage.

**Comment by sphaero** [comment]
a unitypackage file is just a tar.gz file, so you could write a script for it?

**Comment by FatihBAKIR** [comment]
@sphaero @alimoeeny 
I've made some major changes, including the ability to unpack unitypackages. The new version is in the dev branch. Let me know if there are any problems.
